### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by lyzqm123** [q-raccoon/python-model-serving-sample#3]
- [ ] Containerization (docker, k8s)
  - [x] model inference docker
    - GPU inference 적용 [_TF-TensorRT까지 적용하기?_]
  - [ ] model training docker
  - [x] model store docker
- [ ] Stress test (locust.io ?)
- [ ] GPU inference + TF-TensorRT
- [ ] Batch inference
